# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='book',
            new_name='books',
        ),
    ]
